services:
  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: mlflow
    ports:
      - 5001:5001
    volumes:
      - ./mlflow/mlruns:/mlruns
      - ./mlflow/mlartifacts:/mlartifacts

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/cached_scrapings:/app/cached_scrapings
      - ./backend/prompts:/app/prompts
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
      - ./backend/.python-version:/app/.python-version
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/firebase-adminsdk.json:/app/firebase-adminsdk.json
    environment:
      - MLFLOW_URI=${MLFLOW_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ROYALE_API_URL=${ROYALE_API_URL}
      - ROYALE_API_KEY=${ROYALE_API_KEY}
      - PROMPTS_DIR=${PROMPTS_DIR}
      - SCRAPED_DIR=${SCRAPED_DIR}
      - FIREBASE_SDK_JSON=${FIREBASE_SDK_JSON}
