services:
  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: mlflow
    ports:
      - 5001:5001
    volumes:
      - ./mlflow/mlruns:/mlruns
      - ./mlflow/mlartifacts:/mlartifacts

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - MLFLOW_URI=${MLFLOW_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ROYALE_API_URL=${ROYALE_API_URL}
      - ROYALE_API_KEY=${ROYALE_API_KEY}
      - PROMPTS_DIR=${PROMPTS_DIR}
      - FIREBASE_SDK_JSON=${FIREBASE_SDK_JSON}
