{
 "title": "Model Performance (Regression)",
 "time": { "from": "2021-02-01T02:00:00.000Z", "to": "2021-02-01T12:00:00.000Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ME",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "ME",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  me\nFROM model_performance\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MAE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "ME",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  mae\nFROM model_performance\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MAPE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  mape\nFROM model_performance\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Aggregated Metrics: ME & MAE (in time)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "legendFormat": "ME",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  me AS \"ME\"\nFROM model_performance\nORDER BY 1"
    },
    {
     "legendFormat": "MAE",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  mae AS \"MAE\"\nFROM model_performance\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Aggregated Metrics: RMSE (in time)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "legendFormat": "MAE",
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  rmse AS \"RMSE\"\nFROM model_performance\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MAPE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \n  \"mape\" AS \"MAPE\", \n  \"timestamp\" AS \"time\" \nFROM model_performance"
    }
   ]
  }
 ]
}