services:
  
  monitoring-db:
    image: postgres:17.5-alpine
    container_name: monitoring-db-postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "monitoring_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
    - 5432:5432
    networks:
      - monitoring
    volumes:
      - monitoring_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d monitoring_db -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    networks:
      - monitoring
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - 3000:3000
    user: "0"
    volumes:
      - ./grafana/config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./grafana/config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./grafana/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      monitoring-db:
        condition: service_healthy

volumes:
  monitoring_db_data: {}
  grafana_data: {}

networks:
  monitoring:
    name: monitoring

